### ISSUE TITLE
Doesn't work (macOS 14.6)

### ISSUE THREAD

**Issue by transoceanic2000** [Wylan/nova-rails-migrations#1]
Attempting to run either command fails.

Nova version: 1.1 (Build 207005)
Extension version: 1.0.1
macOS version: 10.14.6 (Mojave)

Exceptions are consistently written to the extension console:

```
Rails Migrations[0:31:05.051000] Extension encountered an uncaught exception:
/Users/Bruce/Library/Application Support/Nova/Extensions/wylan.RailsMigrations/Scripts/rails-migrations.js (Line 18, Column 0)
SyntaxError: Unexpected token '.'
    [native code]
    file:///Users/Bruce/Library/Application%20Support/Nova/Extensions/wylan.RailsMigrations/Scripts/main.js:1:92
```

Judging by the line number an the error message it looks like it may not like the null propagation operator `?.`. [MDN shows](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Browser_compatibility) that this was only supported from Safari 13.1 onwards, so I wonder if this isn't supported in Mojave's version of JavaScriptCore (as Mojave originally shipped with Safari 12).

Is it feasible to adjust the code to use explicit null checks rather than the null propagation operator?

**Comment by Wylan** [comment]
Thanks for the detailed bug report! 

Looks like you were totally correct about the cause. Thats what I get for not testing it against Mojave 🤦. 

1.0.2 should be available on the extension library now 😊
