### ISSUE TITLE
Nova 4 Compatibility

### ISSUE THREAD

**Issue by jonathan-wondereur** [Wylan/nova-rails-migrations#2]
It seems the plugin does not work with Nova V4

**Comment by Wylan** [comment]
Thanks for bringing this to my attention. I'll work on getting this fixed ASAP!

**Comment by jonathan-wondereur** [comment]
Thanks, more specifically it is the open latest migration that is not working, the open migration seems to be working. This is all I get for an error message:

![image](https://user-images.githubusercontent.com/38539725/104359350-8c1abc00-54dd-11eb-98f0-fb692c1e0e91.png)

**Comment by jonathan-wondereur** [comment]
... never mind ... it happens with the opening of a file with the chose migration as well ... seems to be an issue with the opening of the file ...

**Comment by Wylan** [comment]
Yeah, looks like something about the openFile API changed (or probably was just enforced that wasn't before). If you update to version 1.0.3 you should be all set! 😄

**Comment by jonathan-wondereur** [comment]
Thanks for the quick fix!
